#!/bin/bash

export SP_TWITTER_KEY=<TWITTER_KEY>
export SP_TWITTER_SECRET=<TWITTER_SECRET>
export SP_TWITTER_BEARERTOKEN=<TWITTER_BEARER_TOKEN>
export SP_TWITTER_ACCESSTOKEN=<TWITTER_ACCESS_TOKEN>
export SP_TWITTER_ACCESSSECRET=<TWITTER_ACCESS_SECRET>